language: node_js
node_js:
  - 'iojs'
before_install:
- npm install npm -g
before_script:
- npm install
script: make build
addons:
  sauce_connect: true
env:
  global:
    - secure: qpUzxbFrY8pfNhZ/WRhf0EJLWMpKoWMsVxNm8vJ+1qSmYAYH4x/zYOr7ATnZrA1LfETJlgqxD0ip7mw7wgxEM5fsaJ87plZOxFXTyf2r7BlZWQveqnHBfSLaDHJnxcID1sogizQu/oFSI+joooENWzcoqic81hSrsmM5WsN1IisZ8b73b8E6OA5nUdxbzAnAuZP68k18BCmLoAJDjmbaizjwvjdQUfsNVY+Xxl2ZAyh3FO2l7tVq96kOErR7waPLBLK+eJYTzqh4boeGhj5wplg7XlqzadBQN6QR80o/14rccmlvvajhTqkUOcBK4KJD/QugWkVcvqIhet1W67UaRdxJcxSv9oIX2OfgOrACx2LqFlNTwE1QuayH3zPrREyHERFI1tO9YmNn1vNR9ngwR46c8iHKT3vWXW672dhXS2HrLPDjr3RdPhTXvtPMnoQ63FL2MkkpmffSQOqc1JoYfzNZFGy+2WYO547TJKq7/AIvVqhX56TwJ1HbR1M8nFqL6NxSRCQ23bYAgWAfrR8vGIJDYDZQ/2SJuGBdQ+rd8zzYelnC1XUA2l4iYJ70w/juU9wRCOvueyDoRj71YZgNzFET+XXAjyWC+JQiJ8Xh+tmca8zYI0xXU4TA5ftGK+l/JEfz+z1AsHC2xO+wbu9+I32Ol55seV+YCexqcUETvYE=
    - secure: I7WTRRKNYPmFg18vfxXNyUsW++6cCeOieWJziXpZEg4dFocBrI5WrvM1WUCCPb2CLpPSQTc6uL45zT1QJE8GwHNQfIeYeXgQoFrLEdHkTXjnY0yyPTKdSVSGjls2uaWkCvogwOZYAcCkYwtSqLfLjKJTo9++hqQYhn1HWVNCn9r/C7k+PLrUWY31JmeEQ4E3QvWA/qaHyGZIWUCZi8T8yFyPFN6C9SHCO4/XHFi7BKDjxDy3VrTjGjZOWkr6S7jEJe7DMJnLweBChCLi8b/P3B6kGu7xsqf7yAC6G3TB8nyrho45unVr6p9lQETgmqSn8ihWq3I0vIBXZB1pRQ+dO4KZZqFPo7in/Jw5dEcaV8UIcTAGEC8jwSEqLP45ICRyWV1opcTXpy94XXG3mHcDCepOZWj1TM41ZQSm0pYgasfZFuupqPnxGRmf7qBhuBtOWvaNCyULA/xBp7GKTgOZ593pgJygg26Vrl3VX1Pgs4DN0AChDng9SaDRKirBo5JyZtJVlG00T7hhqj+z5WTOPBG76YQtWZK7Sb/SfMjBhuB4JKpOZq4Furl/H7KEHsP8yi6zPDalzMURqCT2rylml+n/zLLHskqonaME6EoAq75AC2Iionp6htKx30hKzJHupZb3Be6INqwkxRJaHumkUvQIpfLEkftneAV88o7kp2Q=
